apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lw-is-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/frantz-dimitri-kube-cloud/argocd-devops.git
    targetRevision: develop
    path: lw-is-website-k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: lw-is